usr/bin/
usr/share/
data/ukui-media-volume-control-applet.desktop /etc/xdg/autostart
data/icons/* usr/share/ukui-media/icons/hicolor/
data/sounds/ukui-sounds-default.xml usr/share/ukui-media/sounds/
ukui-volume-control/ukui-volume-control-applet-qt/build/ukui-media-volume-control-applet-qt usr/bin/
ukui-volume-control/ukui-volume-control-applet-qt/translations/ukui-media-volume-control-applet-qt-zh_CN.qm usr/share/ukui-media/translations/

